### ISSUE TITLE
Map Location issue

### ISSUE THREAD

**Issue by bb-varun** [publicv-org/publicv#184] opened 2021-08-07 11:28 UTC
User Story:-
As a user I login and it shows me a map based on my location lat long.

Problem:-
When I am logging in (from India)  it shows Florida(USA) as my default location on the Map.

Solution:-
When a user logins from any of the location ,It should show the location (from where the user login) or else it should the default Location(Italy's Map).
![PubliCV_ Digital](https://user-images.githubusercontent.com/87966762/128598630-790ce9ab-8973-4d96-9c97-3d9e71169c71.png)

**Comment by darmenise** [comment] 2021-08-07 14:55
This is a duplicate of #177 but better reported! 🙂  
I don't think that the default location should be Italy, for this is an international platform.

There are actually 3 things to be done:

1. Improve the map centering (so that when you access from India you see India at the center)
2. Zoom out, so that we don't need to be too precise.
3. The default location could be the whole world, provided it's not a problem form a memory perspective (because we'll need to show the map clusters for all of the results)

**Comment by bb-varun** [comment] 2021-08-07 15:47
Thank you @darmenise . Will get this done for sure.

**Closed** 2021-08-12 09:22 UTC
Labels: bug
