### ISSUE TITLE
ActionView::MissingTemplate: Missing template contacts/errors

### ISSUE THREAD

**Issue by darmenise** [publicv-org/publicv#174] opened 2021-08-03 15:28 UTC
This happened while I was beta-testing the send of a message to a user (in this case myself). Apparently I forgot some mandatory field and, instead of showing me the validation error, I got a 500.

Sentry Issue: [PUBLICV-3](https://sentry.io/organizations/corsidia/issues/2526365726/?referrer=github_integration)

```
ActionView::MissingTemplate: Missing template contacts/errors with {:locale=>[:it, :en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
  * "/app/app/views"
  * "/app/vendor/bundle/ruby/2.4.0/gems/kaminari-core-1.2.1/app/views"
  * "/app/vendor/bundle/ruby/2.4.0/gems/devise-i18n-1.8.0/app/views"
  * "/app/vendor/bundle/ruby/2.4.0/gems/devise-4.7.1/app/views"

  app/controllers/contacts_controller.rb:14:in `create'
    render 'contacts/errors'
...
(119 additional frame(s) were not displayed)
```

**Comment by vishal-bluebash** [comment] 2021-08-04 06:26
https://github.com/publicv-org/publicv/pull/170
https://github.com/publicv-org/publicv/issues/169

@darmenise this is duplicate of above

**Comment by darmenise** [comment] 2021-08-04 09:21
You're right, added the duplicate label.

**Closed** 2021-08-18 11:52 UTC
Labels: duplicate
