### ISSUE TITLE
[CV Format] - Add the area "Courses, Certifications, Professional Achievements"

### ISSUE THREAD

**Issue by ValerioVillani** [publicv-org/publicv#265] opened 2021-12-16 12:12 UTC
Right now we are asking our users to fulfil 6 boxes:

Professional Goals - Experience - Education - Languages - Skills - Other Info.

How About adding a new box? 

I was thinking about Courses, Certifications and Professional Achievements".

For many reasons:

- When I used to be and HeadHunter, in order to better sell the candidates to my clients I used to share with them candidates' achievements and certifications.

- Since that Certifications don't contribute in a proper way (at least in common knowledge) to our "education" I think it's way better for them to have their own box.

-  Helping the users to share with us their latest courses (Market resources).

**Comment by duarme** [comment] 2021-12-19 09:39
This is almost a duplicate of #264 let's discuss it @ValerioVillani :)

**Closed** 2021-12-28 09:29 UTC
Labels: duplicate, improvement, discussion
